---
# tasks file for k8s-master
- name: cluster 設定状況の確認
  shell: ls /etc/kubernetes/manifests | wc -l
  ignore_errors: yes
  changed_when: False
  register: cluster_init_status

- name: k8s cluster の初期化
  when: cluster_init_status.stdout|int == 0 
  shell: |
    kubeadm init {{ kubeadm_init_opts }}
  register: kubeadm_init

- name: Homeディレクトリの取得
  shell: |
    getent passwd {{ ansible_user }} | cut -d: -f6
  changed_when: False
  register: user_home
  become: False

- name: グループIDの取得
  shell: |
    getent passwd {{ ansible_user }} | cut -d: -f4
  changed_when: False
  register: user_gid
  become: False

- name: k8s コンフィグ用ディレクトリ作成
  file:
    path: "{{ user_home.stdout }}/.kube/"
    state: directory
  become: False

- name: admin.conf のコピー
  when: kubeadm_init is succeeded
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ user_home.stdout }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ user_gid.stdout }}"
    remote_src: true

- name: Weave Net のインストール
  when: cluster_init_status.stdout|int == 0 
  shell: |
    export KUBECONFIG={{ user_home.stdout }}/.kube/config;
    kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')
